import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Filter, Layers3, X } from 'lucide-react';
import { BlockRequest, BlockStatus, Department, RailwayZoneCode, User } from '../types';
import { AffectedTrainsModal } from './AffectedTrainsModal';
import { extractZoneCode, getCorridorCapacity, getSectionTimetable, matchesZoneScope } from '../data/railwayOperations';
import { HorizonPlanResponse, requestHorizonPlan } from '../services/solverService';
import { coaAdapter } from '../integrations/coaAdapter';

interface GanttChartProps { currentUser: User; allRequests: BlockRequest[]; activeZone?: RailwayZoneCode; onViewRequestDetail: (request: BlockRequest) => void; }
type StatusFilter = 'ALL' | BlockStatus | 'OPTIMIZED';
type Horizon = 'DAY' | 'WEEK' | 'MONTH';
interface TimelineWindow { start: number; end: number; }

const STATUS_OPTIONS: Array<{ value: StatusFilter; label: string }> = [
  { value: 'ALL', label: 'All statuses' }, { value: 'PENDING', label: 'Pending' }, { value: 'APPROVED', label: 'Approved' },
  { value: 'MODIFIED_APPROVED', label: 'Modified approved' }, { value: 'REJECTED', label: 'Rejected' }, { value: 'COMPLETED', label: 'Completed' }, { value: 'OPTIMIZED', label: 'AI optimized' },
];
const timeToMinutes = (value: string): number => { const [hours, minutes] = (value || '00:00').split(':').map(Number); return Math.max(0, Math.min(1440, (hours || 0) * 60 + (minutes || 0))); };
const minutesToTime = (value: number): string => `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;
const formatHours = (minutes: number): string => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const dateToKey = (date: Date): string => date.toISOString().slice(0, 10);
const dateFromKey = (key: string): Date => new Date(`${key || dateToKey(new Date())}T00:00:00`);
const addDays = (key: string, days: number): string => { const date = dateFromKey(key); date.setDate(date.getDate() + days); return dateToKey(date); };
const displayDate = (key: string, options?: Intl.DateTimeFormatOptions): string => dateFromKey(key).toLocaleDateString('en-IN', options || { day: '2-digit', month: 'short' });
const departmentLabel = (department: Department): string => department === 'ENGINEERING' ? 'ENG' : department === 'ST' ? 'S&T' : 'TRD';
const departmentClasses = (department: Department): string => ({ ENGINEERING: 'border-amber-600 bg-amber-500 text-slate-950', ST: 'border-indigo-700 bg-indigo-600 text-white', TRD: 'border-red-700 bg-red-600 text-white' }[department]);
const getRequestWindow = (request: BlockRequest): TimelineWindow => { const start = timeToMinutes(request.approvedStartTime || request.requestedStartTime || '00:00'); let end = timeToMinutes(request.approvedEndTime || request.requestedEndTime || '01:00'); if (end <= start) end = Math.min(1440, start + Math.max(request.durationMinutes || 60, 15)); return { start, end }; };
const getSectionCapacityMinutes = (section: string): number => Math.max(60, Math.round((getCorridorCapacity(section)[0]?.maxHourlyCapacity || 6) * 60));
const hasTrainConflict = (request: BlockRequest, window: TimelineWindow): boolean => getSectionTimetable(request.section).some((entry) => Math.max(window.start, timeToMinutes(entry.arrivalTime)) < Math.min(window.end, timeToMinutes(entry.departureTime)));

const Metric: React.FC<{ label: string; value: string | number; warning?: boolean }> = ({ label, value, warning }) => <div className={`rounded border px-2 py-1.5 ${warning ? 'border-red-200 bg-red-50' : 'border-slate-200 bg-white'}`}><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</div><div className={`mt-0.5 text-sm font-bold ${warning ? 'text-red-700' : 'text-[#003366]'}`}>{value}</div></div>;
const Select: React.FC<{ label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }> = ({ label, value, onChange, options }) => <label className="text-[11px] font-semibold text-slate-600">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded border border-slate-300 bg-white px-2 py-1.5 text-xs text-slate-700">{options.length ? options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>) : <option value="">No data</option>}</select></label>;
const DepartmentBadge: React.FC<{ department: Department }> = ({ department }) => <span className={`rounded border px-1.5 py-0.5 text-[9px] font-bold ${departmentClasses(department)}`}>{departmentLabel(department)}</span>;

export const GanttChart: React.FC<GanttChartProps> = ({ currentUser, allRequests, activeZone = 'ALL', onViewRequestDetail }) => {
  const [horizon, setHorizon] = useState<Horizon>('DAY');
  const [selectedDepartment, setSelectedDepartment] = useState<'ALL' | Department>('ALL');
  const [selectedDate, setSelectedDate] = useState('');
  const [selectedStatus, setSelectedStatus] = useState<StatusFilter>('ALL');
  const [selectedSection, setSelectedSection] = useState('ALL');
  const [selectedPriority, setSelectedPriority] = useState('ALL');
  const [selectedRequest, setSelectedRequest] = useState<BlockRequest | null>(null);
  const [affectedRequest, setAffectedRequest] = useState<BlockRequest | null>(null);
  const [horizonPlan, setHorizonPlan] = useState<HorizonPlanResponse | null>(null);
  const [planLoading, setPlanLoading] = useState(false);
  const scopedRequests = useMemo(() => allRequests.filter((request) => (currentUser.role === 'SECTION_CONTROLLER' || request.department === currentUser.department) && matchesZoneScope(request, extractZoneCode(activeZone))), [allRequests, currentUser, activeZone]);
  const dates = useMemo(() => Array.from(new Set(scopedRequests.map((request) => request.requestedDate).filter(Boolean))).sort(), [scopedRequests]);
  const effectiveDate = selectedDate || dates[0] || dateToKey(new Date());
  const sections = useMemo(() => Array.from(new Set(scopedRequests.map((request) => request.section).filter(Boolean))).sort(), [scopedRequests]);
  const filteredRequests = useMemo(() => scopedRequests.filter((request) => (selectedDepartment === 'ALL' || request.department === selectedDepartment) && (selectedStatus === 'ALL' || (selectedStatus === 'OPTIMIZED' ? Boolean(request.aiOptimized) : request.status === selectedStatus)) && (selectedSection === 'ALL' || request.section === selectedSection) && (selectedPriority === 'ALL' || request.priority === selectedPriority) && (horizon !== 'DAY' || request.requestedDate === effectiveDate)), [scopedRequests, selectedDepartment, selectedStatus, selectedSection, selectedPriority, horizon, effectiveDate]);
  const backlog = useMemo(() => scopedRequests.filter((request) => request.requestedDate < dateToKey(new Date()) && (request.status === 'PENDING' || request.status === 'REJECTED' || request.controllerRemarks?.toLowerCase().includes('deferred'))), [scopedRequests]);
  const conflictIds = useMemo(() => new Set(filteredRequests.filter((request) => hasTrainConflict(request, getRequestWindow(request))).map((request) => request.id)), [filteredRequests]);
  const totalMinutes = filteredRequests.reduce((sum, request) => sum + (request.durationMinutes || 0), 0);
  const totalCapacityMinutes = filteredRequests.reduce((sum, request) => sum + getSectionCapacityMinutes(request.section), 0);
  const openRequest = (request: BlockRequest) => { setSelectedRequest(request); setAffectedRequest(request); };
  const generatePlan = async () => { setPlanLoading(true); setHorizonPlan(await requestHorizonPlan(filteredRequests, horizon === 'WEEK' ? 7 : 30, effectiveDate)); setPlanLoading(false); };
  useEffect(() => { setHorizonPlan(null); }, [horizon, effectiveDate]);
  return <section className="mb-6 overflow-hidden rounded-xl border border-[#003366]/20 bg-white shadow-sm" aria-labelledby="gantt-chart-title">
    <div className="border-b-4 border-[#FF9900] bg-[#003366] px-4 py-4 text-white sm:px-5"><div className="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between"><div className="flex min-w-0 items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-white/10"><Layers3 className="h-5 w-5 text-[#FF9900]" /></div><div><h2 id="gantt-chart-title" className="text-base font-bold">Maintenance Planning</h2><p className="mt-0.5 text-xs text-blue-100">Interactive block occupancy, workload, and affected train impact</p></div></div><div className="flex items-center rounded-lg border border-white/20 bg-white/10 p-1">{(['DAY', 'WEEK', 'MONTH'] as Horizon[]).map((mode) => <button key={mode} type="button" onClick={() => setHorizon(mode)} className={`px-3 py-1.5 text-[11px] font-bold ${horizon === mode ? 'rounded bg-[#FF9900] text-[#003366]' : 'text-blue-100 hover:text-white'}`}>{mode === 'DAY' ? 'Daily' : mode === 'WEEK' ? 'Weekly' : 'Monthly'}</button>)}</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-6"><Metric label="Visible blocks" value={filteredRequests.length} /><Metric label="Backlog" value={backlog.length} warning={backlog.length > 0} /><Metric label="Conflicts" value={conflictIds.size} warning={conflictIds.size > 0} /><Metric label="Scheduled hours" value={formatHours(totalMinutes)} /><Metric label="Sections" value={sections.length} /><Metric label="Capacity load" value={`${totalCapacityMinutes ? Math.round((totalMinutes / totalCapacityMinutes) * 100) : 0}%`} warning={totalMinutes > totalCapacityMinutes} /></div><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-5"><Select label="Department" value={selectedDepartment} onChange={(value) => setSelectedDepartment(value as 'ALL' | Department)} options={['ALL', 'ENGINEERING', 'ST', 'TRD'].map((value) => ({ value, label: value === 'ALL' ? 'All departments' : value === 'ENGINEERING' ? 'ENG' : value === 'ST' ? 'S&T' : 'TRD' }))} /><Select label="Anchor date" value={effectiveDate} onChange={setSelectedDate} options={dates.map((value) => ({ value, label: displayDate(value, { weekday: 'short', day: '2-digit', month: 'short' }) }))} /><Select label="Status" value={selectedStatus} onChange={(value) => setSelectedStatus(value as StatusFilter)} options={STATUS_OPTIONS} /><Select label="Section" value={selectedSection} onChange={setSelectedSection} options={[{ value: 'ALL', label: 'All sections' }, ...sections.map((value) => ({ value, label: value }))]} /><Select label="Priority" value={selectedPriority} onChange={setSelectedPriority} options={[{ value: 'ALL', label: 'All priorities' }, { value: 'SAFETY_CRITICAL', label: 'Safety critical' }, { value: 'URGENT', label: 'Urgent' }, { value: 'ROUTINE_PLANNED', label: 'Routine planned' }]} /></div></div>
    <div className="grid gap-4 p-3 sm:p-5 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-3 text-[11px] text-slate-500"><span className="inline-flex items-center gap-1 font-semibold"><Filter className="h-3.5 w-3.5" /> Tap a block for train impact</span><DepartmentBadge department="ENGINEERING" /><DepartmentBadge department="ST" /><DepartmentBadge department="TRD" />{horizon !== 'DAY' && <button type="button" onClick={generatePlan} disabled={planLoading} className="rounded bg-[#003366] px-2.5 py-1.5 text-[10px] font-bold text-white disabled:opacity-60">{planLoading ? 'Generating...' : 'Generate plan'}</button>}{horizonPlan?.fallbackUsed && <span className="rounded border border-amber-300 bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-800">Local fallback</span>}</div>{horizon === 'DAY' && <DayView requests={filteredRequests} date={effectiveDate} onOpen={openRequest} />}{horizon !== 'DAY' && horizonPlan && <HorizonView plan={horizonPlan} />}{horizon === 'WEEK' && !horizonPlan && <WeekView requests={scopedRequests} anchor={effectiveDate} onOpen={openRequest} />}{horizon === 'MONTH' && !horizonPlan && <MonthView requests={scopedRequests} anchor={effectiveDate} onOpen={openRequest} />}</div><aside className="space-y-4">{selectedRequest && <DetailCard request={selectedRequest} onClose={() => setSelectedRequest(null)} onView={() => onViewRequestDetail(selectedRequest)} />}</aside></div><AffectedTrainsModal request={affectedRequest} isOpen={Boolean(affectedRequest)} onClose={() => setAffectedRequest(null)} />
  </section>;
};

const DayView: React.FC<{ requests: BlockRequest[]; date: string; onOpen: (request: BlockRequest) => void }> = ({ requests, date, onOpen }) => { const tracks: Record<string, BlockRequest[]> = {}; requests.forEach((request) => { (tracks[request.section] ||= []).push(request); }); return <div className="overflow-x-auto touch-pan-x rounded-lg border border-[#003366]/20"><div className="min-w-[1500px]"><div className="grid grid-cols-[190px_minmax(1240px,1fr)] border-b border-[#003366]/20 bg-[#003366] text-white"><div className="sticky left-0 z-10 border-r border-white/20 bg-[#003366] px-3 py-2 text-[10px] font-bold uppercase tracking-wide">Section / track</div><div className="grid" style={{ gridTemplateColumns: 'repeat(96, minmax(0, 1fr))' }}>{Array.from({ length: 96 }, (_, index) => <div key={index} className={`border-r border-white/10 py-2 text-center font-mono text-[8px] text-blue-100 ${index % 4 ? 'text-transparent' : ''}`}>{index % 4 === 0 ? `${String(index / 4).padStart(2, '0')}:00` : '-'}</div>)}</div></div>{Object.entries(tracks).map(([section, sectionRequests]) => <div key={section} className="grid grid-cols-[190px_minmax(1240px,1fr)] border-b border-slate-100"><div className="sticky left-0 z-10 border-r border-slate-200 bg-white px-3 py-3"><div className="font-mono text-xs font-bold text-[#003366]">{section}</div><div className="mt-1 text-[10px] text-slate-500">{sectionRequests.length} blocks - {date}</div></div><div className="relative min-h-[74px] bg-white" style={{ backgroundImage: 'linear-gradient(to right, rgba(0,51,102,.15) 1px, transparent 1px)', backgroundSize: `${100 / 96}% 100%` }}>{sectionRequests.map((request) => <BlockButton key={request.id} request={request} onOpen={onOpen} />)}</div></div>)}</div></div>; };
const BlockButton: React.FC<{ request: BlockRequest; onOpen: (request: BlockRequest) => void }> = ({ request, onOpen }) => { const window = getRequestWindow(request); const left = `${(window.start / 1440) * 100}%`; const width = `${Math.max(((window.end - window.start) / 1440) * 100, 1.5)}%`; return <button type="button" onClick={() => onOpen(request)} title={`${request.id} - view affected trains`} className={`absolute top-2 min-h-[42px] touch-manipulation rounded border px-2 text-left text-[10px] font-bold shadow-sm transition hover:brightness-95 focus:outline-none focus:ring-2 focus:ring-[#FF9900] ${departmentClasses(request.department)}`} style={{ left, width }}><span className="block truncate">{departmentLabel(request.department)} · {request.id}</span><span className="block truncate text-[9px] font-medium opacity-90">{minutesToTime(window.start)}-{minutesToTime(window.end)}</span></button>; };

const WeekView: React.FC<{ requests: BlockRequest[]; anchor: string; onOpen: (request: BlockRequest) => void }> = ({ requests, anchor, onOpen }) => <div className="grid gap-2 md:grid-cols-7">{Array.from({ length: 7 }, (_, index) => { const date = addDays(anchor, index); const dayRequests = requests.filter((request) => request.requestedDate === date); const minutes = dayRequests.reduce((sum, request) => sum + (request.durationMinutes || 0), 0); return <div key={date} className="min-h-[170px] rounded-lg border border-[#003366]/15 bg-slate-50/60 p-2"><div className="border-b border-slate-200 pb-2"><div className="text-[10px] font-bold uppercase text-slate-500">{displayDate(date, { weekday: 'short' })}</div><div className="font-mono text-xs font-bold text-[#003366]">{displayDate(date)}</div></div><div className="mt-2 text-lg font-bold text-[#003366]">{formatHours(minutes)}</div><div className="text-[10px] text-slate-500">scheduled workload</div><div className="mt-3 space-y-1">{dayRequests.slice(0, 4).map((request) => <button key={request.id} type="button" onClick={() => onOpen(request)} className={`block min-h-[32px] w-full truncate rounded border px-1.5 py-1 text-left text-[10px] font-bold ${departmentClasses(request.department)}`}>{request.id}</button>)}</div></div>; })}</div>;

const MonthView: React.FC<{ requests: BlockRequest[]; anchor: string; onOpen: (request: BlockRequest) => void }> = ({ requests, anchor, onOpen }) => <div className="grid grid-cols-7 gap-px overflow-hidden rounded-lg border border-slate-200 bg-slate-200">{Array.from({ length: 28 }, (_, index) => { const date = addDays(anchor, index); const dayRequests = requests.filter((request) => request.requestedDate === date); const minutes = dayRequests.reduce((sum, request) => sum + (request.durationMinutes || 0), 0); const conflict = dayRequests.some((request) => hasTrainConflict(request, getRequestWindow(request))); return <button key={date} type="button" onClick={() => dayRequests[0] && onOpen(dayRequests[0])} className={`min-h-[94px] bg-white p-2 text-left hover:bg-blue-50 ${conflict ? 'bg-red-50 ring-1 ring-inset ring-red-300' : ''}`}><div className="flex items-center justify-between"><span className="text-[10px] font-bold text-slate-500">{displayDate(date, { weekday: 'short', day: '2-digit' })}</span>{conflict && <AlertTriangle className="h-3.5 w-3.5 text-red-600" />}</div><div className={`mt-3 text-sm font-bold ${conflict ? 'text-red-700' : 'text-[#003366]'}`}>{formatHours(minutes)}</div><div className="text-[10px] text-slate-400">{dayRequests.length} blocks</div></button>; })}</div>;

const HorizonView: React.FC<{ plan: HorizonPlanResponse }> = ({ plan }) => <div className="grid gap-2 md:grid-cols-7">{plan.dailyPlan.map((day) => <div key={day.date} className="min-h-[190px] rounded-lg border border-[#003366]/15 bg-slate-50/60 p-2"><div className="border-b border-slate-200 pb-2"><div className="text-[10px] font-bold uppercase text-slate-500">{displayDate(day.date, { weekday: 'short' })}</div><div className="font-mono text-xs font-bold text-[#003366]">{displayDate(day.date)}</div></div><div className="mt-2 space-y-1 text-[10px] text-slate-600">{day.bundledWindows.map((window, index) => <div key={`${day.date}-bundle-${index}`} className="rounded border border-indigo-200 bg-indigo-50 px-1.5 py-1"><strong>{window.section}</strong> · bundled {window.durationMinutes}m</div>)}{day.standalone.map((request) => <div key={request.id} className="rounded border border-slate-200 bg-white px-1.5 py-1">{request.id} · {request.durationMinutes}m</div>)}</div>{Object.entries(day.capacityUtilisationPercent).map(([section, rawValue]) => { const value = Number(rawValue); const forecast = coaAdapter.getGoodsForecast(section, plan.horizonDays)[day.dayIndex]; return <div key={section} className="mt-2"><div className="flex justify-between text-[9px] text-slate-500"><span>{section}</span><span>{value}%</span></div><div className="h-1.5 overflow-hidden rounded bg-slate-200"><div className={`h-full ${value > 100 ? 'bg-red-500' : 'bg-[#FF9900]'}`} style={{ width: `${Math.min(value, 100)}%` }} /></div><div className="mt-1 text-[9px] text-slate-500">Goods forecast: {forecast?.freightTrainCount || 0} trains</div></div>; })}</div>)}</div>;

const DetailCard: React.FC<{ request: BlockRequest; onClose: () => void; onView: () => void }> = ({ request, onClose, onView }) => <div className="rounded-lg border border-[#003366]/20 bg-white p-3"><div className="flex items-start justify-between"><div><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Selected block</div><div className="font-mono text-sm font-bold text-[#003366]">{request.id}</div></div><button type="button" onClick={onClose} className="rounded p-1 text-slate-400 hover:bg-slate-100" aria-label="Close details"><X className="h-4 w-4" /></button></div><div className="mt-3 grid grid-cols-2 gap-2 text-[11px]"><span>Department <strong>{departmentLabel(request.department)}</strong></span><span>Window <strong>{request.requestedStartTime}-{request.requestedEndTime}</strong></span><span className="col-span-2">Section <strong>{request.section}</strong></span></div><button type="button" onClick={onView} className="mt-3 w-full rounded bg-[#003366] px-3 py-2 text-xs font-bold text-white hover:bg-[#00264d]">Open requisition details</button></div>;
